spring.application.name=price-calculation-service
server.port=8084
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
logging.level.root=INFO
logging.level.com.bookstore.price=DEBUG